// Bakes each avatar body's outline (vendor/orb-mascot) into a plain SVG
// path for the toon characters (web/src/lib/toon), so they draw our bodies
// in ink without a canvas at runtime. Re-run when the vendored core's
// bodies change:
//
//   node scripts/toon-bodies.mjs
//
// The core melts each body together from circles with a goo filter; baking
// that into a path needs a canvas, so this runs it in headless Chromium.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const R = join(dirname(fileURLToPath(import.meta.url)), "..");
const { chromium } = await import(
  join(R, "web/node_modules/playwright/index.mjs")
);
const core = readFileSync(join(R, "web/src/vendor/orb-mascot/core.js"), "utf8");
const BODIES = ["bear", "lemon", "ghost", "cloud", "drop", "stack", "seacow", "flower"];

const browser = await chromium.launch({
  executablePath: process.env.CHROMIUM_PATH || "/opt/pw-browsers/chromium",
});
const page = await browser.newPage();
await page.setContent('<svg id="s" viewBox="-24 -24 248 248"></svg>');
await page.addScriptTag({ content: core });
const baked = await page.evaluate((bodies) => {
  const out = {};
  for (const body of bodies) {
    const svg = document.getElementById("s");
    svg.innerHTML = "";
    const m = new window.Mascot(svg, { preset: "avatar", body, color: "#888888" });
    m.render();
    const raw = m._comp ? m._bakeGoo() : m.sphere.getAttribute("d");
    // One decimal is plenty at any size we draw; it halves the file.
    const d = raw.replace(/-?\d+\.\d+/g, (n) => String(Math.round(Number(n) * 10) / 10));
    const p = document.createElementNS("http://www.w3.org/2000/svg", "path");
    p.setAttribute("d", d);
    svg.appendChild(p);
    const b = p.getBBox();
    out[body] = { d, box: [b.x, b.y, b.width, b.height].map((v) => Math.round(v * 10) / 10) };
  }
  return out;
}, BODIES);
await browser.close();

const lines = [
  "// GENERATED by scripts/toon-bodies.mjs from vendor/orb-mascot. Do not edit.",
  "//",
  "// Each avatar body's outline as one path, in the core's 200-unit box",
  "// (centre 100 100), with its bounding box [x, y, width, height].",
  "",
  'import type { AvatarShape } from "../../api/memberTypes";',
  "",
  "export interface BodyOutline {",
  "  readonly d: string;",
  "  readonly box: readonly [number, number, number, number];",
  "}",
  "",
  "export const BODY_OUTLINES: Readonly<Record<AvatarShape, BodyOutline>> = {",
];
for (const body of BODIES) {
  const { d, box } = baked[body];
  lines.push(`  ${body}: {`, `    d: "${d}",`, `    box: [${box.join(", ")}],`, "  },");
}
lines.push("};", "");
writeFileSync(join(R, "web/src/lib/toon/bodies.gen.ts"), lines.join("\n"));
console.log("wrote web/src/lib/toon/bodies.gen.ts");
